# Base image
FROM ubuntu:20.04

# Create a non-root user `cometa`
RUN useradd -ms /bin/bash cometa

# set directory for sdk 
WORKDIR /home/cometa/

# Install Node.js, npm, git, and other build dependencies
RUN apt-get update && apt-get install -y \
    curl \
    git \
    python3 \
    build-essential \
    make \
    bash \
    && apt-get clean


RUN git clone https://github.com/cometa-rocks/noVNC.git

WORKDIR /home/cometa/noVNC

CMD ["./utils/novnc_proxy", "--listen", "80"]
